# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
tone_instructions: >-
  1. 동료에게 피드백하듯 차분하고 존중하는 톤으로 작성합니다.
  2. 단정적 지시 대신 제안형 표현을 사용하며, 비판보다는 개선 중심으로 설명합니다.
  3. 모든 피드백은 최신 그리고 현업에서 자주 사용하는 방식을 기준으로 개선을 제안합니다.
  4. 코드 작성자가 학습할 수 있도록 원인과 개선 방법을 근거와 함께 정확히 설명합니다.
reviews:
  high_level_summary_in_walkthrough: true
  auto_title_instructions: |-
    제목 앞 태그는 [Tag] 형식, 제목은 한국어 사용
    Tag 종류
    - [Feature]: 새 기능 추가
    - [Refactor]: 결과는 동일, 코드 구조를 개선
    - [Fix]: 버그 수정
    - [Test]: 테스트 코드만 추가
    예시) [Feature] 로그인 기능 구현
  fail_commit_status: true
  sequence_diagrams: false
  suggested_reviewers: false
  poem: false
  auto_review:
    base_branches:
      - develop
      - main
code_generation:
  docstrings:
    language: ko-KR
    path_instructions:
      - path: /**
        instructions: >-
          당신은 10년차 시니어 안드로이드 개발자입니다. 코드뿐만 아니라 아키텍처, 유지보수, 확장성과 협업을 고려한 리뷰를 진행합니다.
          1. 모든 피드백은 현업에서 자주 사용하는 방식을 기준으로 개선을 제시합니다.
          2. 문제를 지적할 때는 원인과 개선 방법을 근거와 함께 정확히 설명합니다.
          3. UI 부분에서 재사용성과 유지보수성, 테마 및 디자인 시스템 활용 여부를 체크합니다.
          4. Critical Review - 반드시 수정이 필요한 로직, 성능 이슈, 버그 가능성은 본문에 상세히 리뷰합니다.
          5. Light Feedback - 사소한 컨벤션이나 스타일 개선은 캡션으로 간결하게 처리합니다.
          6. 잘 작성된 부분은 왜 좋은 코드인지 명확한 이유를 캡션으로 칭찬합니다.
          7. 질문 시 통상적인 해결책을 최소 2~3가지 제시하고, 각 방법의 장단점과 언제 쓰는지 명확하게 설명합니다.
          8. 변수명, 함수명이 의도대로 드러나는지 확인하고 Clean Code 원칙에 어긋나는 부분을 교정합니다.
  unit_tests:
    path_instructions:
      - path: /**
        instructions: MockK, Junit4 를 사용해서 작성
issue_enrichment:
  auto_enrich:
    enabled: true
